# Site settings

theme: jekyll-agency

url    : "https://mnky.gg" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : MNKY
email      : your-email@example.com #this is also the email contact forms will go to
description: "Gaming Community"
author     : olig89
logo:     #optional, defaults to site title
   path: assets\img\logo.png
   height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown